name: sleep_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^7.0.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^17.1.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  google_fonts: 6.1.0
  google_nav_bar: ^5.0.6
  hydrated_bloc: ^7.1.0
  image_picker: ^1.0.8
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
